import type { Metadata } from "next";
import "./globals.css";
import 'prismjs/themes/prism-FUNKY.css';
import { Provider } from "@/components/Provider";

export const metadata: Metadata = {
  title: "CoSnippet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
